"""
Energy Dashboard — `content/license_text.py` (split from EnergyDashboard2.py).
"""
from __future__ import annotations

from energy_dashboard.deps import *
# Rich HTML shown on the License tab (also summarized in Help for LicenseTab).
_LICENSE_TAB_HTML = (
    "<div style='font-family:system-ui,Segoe UI,sans-serif;line-height:1.5;"
    "color:#cdd6f4;padding:4px 2px;'>"

    "<p style='margin:0 0 6px 0;color:#a6adc8;'>"
    "<b>Energy Dashboard</b> is released under the "
    "<a href='https://polyformproject.org/licenses/noncommercial/1.0.0/' "
    "style='color:#89b4fa;text-decoration:none;'>"
    "PolyForm Noncommercial License 1.0.0</a>."
    "</p>"
    "<p style='margin:0 0 14px 0;color:#a6adc8;font-size:12px;'>"
    "Required Notice: Copyright &copy; 2026 Aliniant UK Ltd "
    "(<a href='https://aliniant.com' "
    "style='color:#89b4fa;text-decoration:none;'>https://aliniant.com</a>). "
    "All rights reserved. Use of this tool implies acceptance of the licence."
    "</p>"

    "<h3 style='margin:0 0 4px 0;color:#cdd6f4;font-size:13px;'>"
    "PolyForm Noncommercial License 1.0.0"
    "</h3>"

    "<h4 style='margin:10px 0 2px 0;color:#89b4fa;font-size:12px;'>Acceptance</h4>"
    "<p style='margin:0 0 6px 0;font-size:12px;color:#bac2de;'>"
    "In order to get any license under these terms, you must agree to them as "
    "both strict obligations and conditions to all your licenses."
    "</p>"

    "<h4 style='margin:10px 0 2px 0;color:#89b4fa;font-size:12px;'>Copyright License</h4>"
    "<p style='margin:0 0 6px 0;font-size:12px;color:#bac2de;'>"
    "The licensor grants you a copyright license for the software to do "
    "everything you might do with the software that would otherwise infringe "
    "the licensor&apos;s copyright in it for any permitted purpose. However, "
    "you may only distribute the software according to <i>Distribution License</i> "
    "and make changes or new works based on the software according to "
    "<i>Changes and New Works License</i>."
    "</p>"

    "<h4 style='margin:10px 0 2px 0;color:#89b4fa;font-size:12px;'>Distribution License</h4>"
    "<p style='margin:0 0 6px 0;font-size:12px;color:#bac2de;'>"
    "The licensor grants you an additional copyright license to distribute "
    "copies of the software. Your license to distribute covers distributing the "
    "software with changes and new works permitted by <i>Changes and New Works License</i>."
    "</p>"

    "<h4 style='margin:10px 0 2px 0;color:#89b4fa;font-size:12px;'>Notices</h4>"
    "<p style='margin:0 0 6px 0;font-size:12px;color:#bac2de;'>"
    "You must ensure that anyone who gets a copy of any part of the software "
    "from you also gets a copy of these terms or the URL for them above, as "
    "well as copies of any plain-text lines beginning with <code>Required "
    "Notice:</code> that the licensor provided with the software. For example:"
    "</p>"
    "<p style='margin:0 0 6px 14px;font-size:12px;color:#bac2de;font-family:monospace;'>"
    "Required Notice: Copyright &copy; 2026 Aliniant UK Ltd "
    "(https://aliniant.com)"
    "</p>"

    "<h4 style='margin:10px 0 2px 0;color:#89b4fa;font-size:12px;'>"
    "Changes and New Works License</h4>"
    "<p style='margin:0 0 6px 0;font-size:12px;color:#bac2de;'>"
    "The licensor grants you an additional copyright license to make changes "
    "and new works based on the software for any permitted purpose."
    "</p>"

    "<h4 style='margin:10px 0 2px 0;color:#89b4fa;font-size:12px;'>Patent License</h4>"
    "<p style='margin:0 0 6px 0;font-size:12px;color:#bac2de;'>"
    "The licensor grants you a patent license for the software that covers "
    "patent claims the licensor can license, or becomes able to license, that "
    "you would infringe by using the software."
    "</p>"

    "<h4 style='margin:10px 0 2px 0;color:#89b4fa;font-size:12px;'>"
    "Noncommercial Purposes</h4>"
    "<p style='margin:0 0 6px 0;font-size:12px;color:#bac2de;'>"
    "Any noncommercial purpose is a permitted purpose."
    "</p>"

    "<h4 style='margin:10px 0 2px 0;color:#89b4fa;font-size:12px;'>Personal Uses</h4>"
    "<p style='margin:0 0 6px 0;font-size:12px;color:#bac2de;'>"
    "Personal use for research, experiment, and testing for the benefit of "
    "public knowledge, personal study, private entertainment, hobby projects, "
    "amateur pursuits, or religious observance, without any anticipated "
    "commercial application, is use for a permitted purpose."
    "</p>"

    "<h4 style='margin:10px 0 2px 0;color:#89b4fa;font-size:12px;'>"
    "Noncommercial Organizations</h4>"
    "<p style='margin:0 0 6px 0;font-size:12px;color:#bac2de;'>"
    "Use by any charitable organization, educational institution, public "
    "research organization, public safety or health organization, environmental "
    "protection organization, or government institution is use for a permitted "
    "purpose regardless of the source of funding or obligations resulting from "
    "the funding."
    "</p>"

    "<h4 style='margin:10px 0 2px 0;color:#89b4fa;font-size:12px;'>Fair Use</h4>"
    "<p style='margin:0 0 6px 0;font-size:12px;color:#bac2de;'>"
    "You may have &quot;fair use&quot; rights for the software under the law. "
    "These terms do not limit them."
    "</p>"

    "<h4 style='margin:10px 0 2px 0;color:#89b4fa;font-size:12px;'>No Other Rights</h4>"
    "<p style='margin:0 0 6px 0;font-size:12px;color:#bac2de;'>"
    "These terms do not allow you to sublicense or transfer any of your "
    "licenses to anyone else, or prevent the licensor from granting licenses "
    "to anyone else. These terms do not imply any other licenses."
    "</p>"

    "<h4 style='margin:10px 0 2px 0;color:#89b4fa;font-size:12px;'>Patent Defense</h4>"
    "<p style='margin:0 0 6px 0;font-size:12px;color:#bac2de;'>"
    "If you make any written claim that the software infringes or contributes "
    "to infringement of any patent, your patent license for the software "
    "granted under these terms ends immediately. If your company makes such a "
    "claim, your patent license ends immediately for work on behalf of your "
    "company."
    "</p>"

    "<h4 style='margin:10px 0 2px 0;color:#89b4fa;font-size:12px;'>Violations</h4>"
    "<p style='margin:0 0 6px 0;font-size:12px;color:#bac2de;'>"
    "The first time you are notified in writing that you have violated any of "
    "these terms, or done anything with the software not covered by your "
    "licenses, your licenses can nonetheless continue if you come into full "
    "compliance with these terms, and take practical steps to correct past "
    "violations, within 32 days of receiving notice. Otherwise, all your "
    "licenses end immediately."
    "</p>"

    "<h4 style='margin:10px 0 2px 0;color:#89b4fa;font-size:12px;'>No Liability</h4>"
    "<p style='margin:0 0 6px 0;font-size:12px;color:#bac2de;'>"
    "<b>As far as the law allows, the software comes as is, without any "
    "warranty or condition, and the licensor will not be liable to you for any "
    "damages arising out of these terms or the use or nature of the software, "
    "under any kind of legal claim.</b>"
    "</p>"

    "<h4 style='margin:10px 0 2px 0;color:#89b4fa;font-size:12px;'>Definitions</h4>"
    "<p style='margin:0 0 6px 0;font-size:12px;color:#bac2de;'>"
    "The <b>licensor</b> is the individual or entity offering these terms, and "
    "the <b>software</b> is the software the licensor makes available under "
    "these terms."
    "</p>"
    "<p style='margin:0 0 6px 0;font-size:12px;color:#bac2de;'>"
    "<b>You</b> refers to the individual or entity agreeing to these terms."
    "</p>"
    "<p style='margin:0 0 6px 0;font-size:12px;color:#bac2de;'>"
    "<b>Your company</b> is any legal entity, sole proprietorship, or other "
    "kind of organization that you work for, plus all organizations that have "
    "control over, are under the control of, or are under common control with "
    "that organization. <b>Control</b> means ownership of substantially all the "
    "assets of an entity, or the power to direct its management and policies "
    "by vote, contract, or otherwise. Control can be direct or indirect."
    "</p>"
    "<p style='margin:0 0 6px 0;font-size:12px;color:#bac2de;'>"
    "<b>Your licenses</b> are all the licenses granted to you for the software "
    "under these terms."
    "</p>"
    "<p style='margin:0;font-size:12px;color:#bac2de;'>"
    "<b>Use</b> means anything you do with the software requiring one of your "
    "licenses."
    "</p>"
    "</div>"
)


__all__ = [n for n in globals() if not n.startswith('__')]
