#!/usr/bin/env bash
# Install and start powermon-broker systemd unit.
# Reads PostgreSQL + Tasmota settings from ~/.config/PowerModel/EnergyDashboard2.conf
# when present, then writes /etc/default/powermon-broker.
#
# Usage: sudo ./services/install-powermon-broker.sh

set -euo pipefail

if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
  echo "Run as root: sudo $0" >&2
  exit 1
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVICE_NAME=powermon-broker.service
ENV_FILE=/etc/default/powermon-broker
CONF="${POWERMON_QSETTINGS:-/home/user/.config/PowerModel/EnergyDashboard2.conf}"

read_ini() {
  local section="$1" key="$2" default="${3:-}"
  local val=""
  if [[ -f "$CONF" ]]; then
    val="$(awk -F= -v sec="[$section]" -v k="$key" '
      $0 == sec { in_sec=1; next }
      /^\[/ { in_sec=0 }
      in_sec && $1 == k { gsub(/^[^=]*=/, ""); print; exit }
    ' "$CONF")"
  fi
  if [[ -n "$val" ]]; then
    printf '%s' "$val"
  else
    printf '%s' "$default"
  fi
}

PG_HOST="$(read_ini db pg_host localhost)"
PG_PORT="$(read_ini db pg_port 5432)"
PG_DB="$(read_ini db pg_db powermon)"
PG_USER="$(read_ini db pg_user "")"
PG_PASS="$(read_ini db pg_pass "")"
IP_START="$(read_ini tasmota ip_start 222.20.20.101)"
IP_END="$(read_ini tasmota ip_end 222.20.20.112)"

chmod +x "$ROOT/services/powermon-broker-run.sh"

cat >"$ENV_FILE" <<EOF
# Generated by install-powermon-broker.sh from $CONF
POWERMON_PG_HOST=${PG_HOST}
POWERMON_PG_PORT=${PG_PORT}
POWERMON_PG_DB=${PG_DB}
POWERMON_PG_USER=${PG_USER}
POWERMON_PG_PASSWORD=${PG_PASS}
POWERMON_IP_START=${IP_START}
POWERMON_IP_END=${IP_END}
POWERMON_POLL_INTERVAL=30
POWERMON_LISTEN=127.0.0.1:8765
EOF
chmod 600 "$ENV_FILE"

sed "s|WorkingDirectory=.*|WorkingDirectory=${ROOT}|; s|ExecStart=.*|ExecStart=${ROOT}/services/powermon-broker-run.sh|" \
  "$ROOT/services/powermon-broker.service" >"/etc/systemd/system/${SERVICE_NAME}"

systemctl daemon-reload
systemctl enable "${SERVICE_NAME}"
systemctl restart "${SERVICE_NAME}"

echo
systemctl --no-pager status "${SERVICE_NAME}" || true
echo
echo "HTTP health: curl -s http://127.0.0.1:8765/health"
echo "Enable in dashboard: Tasmota tab → 'Use power-monitor broker'"
