#!/usr/bin/env bash
# Install energy-collector as a system systemd service (runs at boot, no GUI needed).
#
# Reads PostgreSQL settings from ~/.config/PowerModel/EnergyDashboard2.conf
# and Growatt defaults from repo .env when not already set.
#
# Usage: sudo ./services/install-energy-collector.sh

set -euo pipefail

if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
  echo "Run as root: sudo $0" >&2
  exit 1
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVICE_NAME=energy-collector.service
ENV_FILE=/etc/default/energy-collector
CONF="${POWERMON_QSETTINGS:-/home/user/.config/PowerModel/EnergyDashboard2.conf}"
# shellcheck source=read-secrets.sh
source "$ROOT/services/read-secrets.sh"

read_ini() {
  local section="$1" key="$2" default="${3:-}"
  local val=""
  if [[ -f "$CONF" ]]; then
    val="$(awk -F= -v sec="[$section]" -v k="$key" '
      $0 == sec { in_sec=1; next }
      /^\[/ { in_sec=0 }
      in_sec && $1 == k { gsub(/^[^=]*=/, ""); print; exit }
    ' "$CONF")"
  fi
  if [[ -n "$val" ]]; then
    printf '%s' "$val"
  else
    printf '%s' "$default"
  fi
}

PG_HOST="$(read_ini db pg_host "$(read_repo_env PG_HOST localhost)")"
PG_PORT="$(read_ini db pg_port "$(read_repo_env PG_PORT 5432)")"
PG_DB="$(read_ini db pg_db "$(read_repo_env PG_DB powermon)")"
PG_USER="$(read_ini db pg_user "$(read_repo_env PG_USER "")")"
PG_PASS="$(read_ini db pg_pass "$(read_repo_env PG_PASSWORD "")")"
GROWATT_USER="$(read_ini growatt user "$(read_repo_env GROWATT_USER "")")"
GROWATT_PASS="$(read_ini growatt pass "$(read_repo_env GROWATT_PASSWORD "")")"
GROWATT_TOKEN="$(read_ini growatt api_token "$(read_repo_env GROWATT_API_TOKEN "")")"
TASMOTA_IP_START="$(read_ini tasmota ip_start "$(read_repo_env TASMOTA_IP_START 222.20.20.101)")"
TASMOTA_IP_END="$(read_ini tasmota ip_end "$(read_repo_env TASMOTA_IP_END 222.20.20.112)")"
# Empty POWERMON_TASMOTA_IPS → scan ip_start..ip_end (matches Tasmota tab range).
TASMOTA_IPS="${POWERMON_TASMOTA_IPS:-}"

chmod +x "$ROOT/services/energy-collector-run.sh"

cat >"$ENV_FILE" <<EOF
# Generated by install-energy-collector.sh
POWERMON_PG_HOST=${PG_HOST}
POWERMON_PG_PORT=${PG_PORT}
POWERMON_PG_DB=${PG_DB}
POWERMON_PG_USER=${PG_USER}
POWERMON_PG_PASSWORD=${PG_PASS}
POWERMON_TASMOTA_IPS=${TASMOTA_IPS}
POWERMON_IP_START=${TASMOTA_IP_START}
POWERMON_IP_END=${TASMOTA_IP_END}
POWERMON_TASMOTA_INTERVAL=30
POWERMON_GROWATT_INTERVAL=60
POWERMON_LOOP_INTERVAL=5
POWERMON_LISTEN=127.0.0.1:8765
POWERMON_GROWATT_USER=${GROWATT_USER}
POWERMON_GROWATT_PASSWORD=${GROWATT_PASS}
POWERMON_GROWATT_TOKEN=${GROWATT_TOKEN}
POWERMON_GROWATT_SERVER=https://server.growatt.com
EOF
chmod 600 "$ENV_FILE"

# Stop user-level collector — it binds the same HTTP port (8765) and duplicates DB writes.
RUN_USER="${SUDO_USER:-user}"
RUN_UID="$(id -u "$RUN_USER" 2>/dev/null || echo "")"
if [[ -n "$RUN_UID" && -d "/run/user/$RUN_UID" ]]; then
  sudo -u "$RUN_USER" env XDG_RUNTIME_DIR="/run/user/$RUN_UID" \
    systemctl --user stop energy-collector.service 2>/dev/null || true
  sudo -u "$RUN_USER" env XDG_RUNTIME_DIR="/run/user/$RUN_UID" \
    systemctl --user disable energy-collector.service 2>/dev/null || true
  sudo -u "$RUN_USER" env XDG_RUNTIME_DIR="/run/user/$RUN_UID" \
    systemctl --user stop powermon-broker.service 2>/dev/null || true
  sudo -u "$RUN_USER" env XDG_RUNTIME_DIR="/run/user/$RUN_UID" \
    systemctl --user disable powermon-broker.service 2>/dev/null || true
fi

sed "s|WorkingDirectory=.*|WorkingDirectory=${ROOT}|; s|ExecStart=.*|ExecStart=${ROOT}/services/energy-collector-run.sh|" \
  "$ROOT/services/energy-collector.service" >"/etc/systemd/system/${SERVICE_NAME}"

# Retire older broker-only system units if present
systemctl stop powermon-broker.service 2>/dev/null || true
systemctl disable powermon-broker.service 2>/dev/null || true

systemctl daemon-reload
systemctl enable "${SERVICE_NAME}"
systemctl restart "${SERVICE_NAME}"

echo
systemctl --no-pager status "${SERVICE_NAME}" || true
echo
echo "Health:  curl -s http://127.0.0.1:8765/health"
echo "Snapshot: curl -s http://127.0.0.1:8765/snapshot | python3 -m json.tool | head"
echo "Logs:     journalctl -u energy-collector -f"
echo "Edit IPs/credentials: sudo nano ${ENV_FILE} && sudo systemctl restart energy-collector"
